-- ======================================================
-- 1. Create User and Grant Privileges (Run as SYSTEM or SYS)
-- ======================================================
-- CREATE USER hr IDENTIFIED BY hr;
-- GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE PROCEDURE TO hr;
-- ALTER USER hr QUOTA UNLIMITED ON USERS;

-- ======================================================
-- 2. Create Tables (Run as HR user)
-- ======================================================

CREATE TABLE Course (
    CourseID NUMBER PRIMARY KEY,
    CourseName VARCHAR2(100) NOT NULL
);

CREATE TABLE Student (
    StudentID NUMBER PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Email VARCHAR2(100) UNIQUE,
    STUDENTPASS VARCHAR2(100)
);

CREATE TABLE Instructor (
    InstructorID NUMBER PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Email VARCHAR2(100) UNIQUE,
    INSTRUCTORPASS VARCHAR2(100)
);

CREATE TABLE Enrollment (
    EnrollmentID NUMBER PRIMARY KEY,
    StudentID NUMBER REFERENCES Student(StudentID),
    CourseID NUMBER REFERENCES Course(CourseID)
);

CREATE TABLE courseSession (
    SessionID NUMBER PRIMARY KEY,
    CourseID NUMBER REFERENCES Course(CourseID),
    SessionDate DATE,
    StartTime VARCHAR2(20),
    EndTime VARCHAR2(20)
);

CREATE TABLE Attendance (
    AttendanceID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    StudentID NUMBER REFERENCES Student(StudentID),
    SessionID NUMBER REFERENCES courseSession(SessionID),
    Status VARCHAR2(20) -- Present, Absent, Excused
);

CREATE TABLE Notification (
    NotificationID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Title VARCHAR2(100),
    Description VARCHAR2(500),
    Type VARCHAR2(20), -- Success, Warning, Info
    RecipientID NUMBER, -- StudentID or NULL for all
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ======================================================
-- 3. Insert Sample Data
-- ======================================================

INSERT INTO Course VALUES (101, 'Software Engineering');
INSERT INTO Course VALUES (102, 'Database Systems');

INSERT INTO Student VALUES (1, 'Ahmed Ali', 'ahmed@example.com', '123');
INSERT INTO Student VALUES (2, 'Sara Mohamed', 'sara@example.com', '123');

INSERT INTO Instructor VALUES (1, 'Dr. Ibrahim', 'admin@example.com', 'admin');
INSERT INTO Instructor VALUES (2, 'Dr. Ahmed', 'ahmed.inst@example.com', '123');

INSERT INTO Enrollment VALUES (1, 1, 101);
INSERT INTO Enrollment VALUES (2, 2, 101);
INSERT INTO Enrollment VALUES (3, 1, 102);

INSERT INTO Notification (Title, Description, Type, RecipientID) 
VALUES ('Welcome!', 'Welcome to the Student Portal', 'Info', 1);
INSERT INTO Notification (Title, Description, Type, RecipientID) 
VALUES ('Low Attendance', 'Your attendance is below 75%', 'Warning', 1);

-- ======================================================
-- 4. Create Stored Procedures (Phase 2 Requirements)
-- ======================================================

-- Procedure to get student count (Select ONE row with OUT parameter)
CREATE OR REPLACE PROCEDURE GET_STUDENT_COUNT (
    p_course_id IN NUMBER,
    p_count OUT NUMBER
) AS
BEGIN
    SELECT COUNT(*) INTO p_count
    FROM Enrollment
    WHERE CourseID = p_course_id;
END;
/

-- Procedure to get sessions (Select MULTIPLE rows)
CREATE OR REPLACE PROCEDURE GET_COURSE_SESSIONS (
    p_course_id IN NUMBER,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT SessionID, CourseID, SessionDate, StartTime, EndTime
    FROM courseSession
    WHERE CourseID = p_course_id;
END;
/

COMMIT;
